
AZURE_OPENAI_API_KEY= "***********************"
AZURE_OPENAI_ENDPOINT = "***********************"
AZURE_OPENAI_EMBEDDING_ENDPOINT = "***********************"
AZURE_OPENAI_API_VERSION = "***********************"
AZUR_DEPLOYMENT_NAME = "***********************"